In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
df = pd.read_csv("../data/raw/gurugram_real_estate.csv")

print("Dataset loaded successfully!")

EmptyDataError: No columns to parse from file

In [7]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download(
    "nikhilmehrahr26/gurgaon-real-estate-dataset"
)

print("Path to dataset files:", path)

Downloading to C:\Users\Akhilesh Kumar Verma\.cache\kagglehub\datasets\nikhilmehrahr26\gurgaon-real-estate-dataset\1.archive...

100%|██████████| 329k/329k [00:00<00:00, 430kB/s]

Extracting files...
Path to dataset files: C:\Users\Akhilesh Kumar Verma\.cache\kagglehub\datasets\nikhilmehrahr26\gurgaon-real-estate-dataset\versions\1

In [8]:
df = pd.read_csv("../data/raw/gurugram_real_estate.csv")

EmptyDataError: No columns to parse from file

In [9]:
import os

print(os.listdir(path))

['data of gurugram real Estate.csv']

In [10]:
import os

csv_file = os.path.join(path, "data of gurugram real Estate.csv")

df = pd.read_csv(csv_file)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [11]:
df.head()

,Price,Status,Area,Rate per sqft,Property Type,Locality,Builder Name,RERA Approval,BHK_Count,Socity,Company Name,Flat Type
0,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,home,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
1,14400000.0,Under Construction,1528,"9,450",3 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,Property In Gurgaon,Approved by RERA,3.0,M3M Antalya Hills Phase I,M3M,Apartment
2,10700000.0,Under Construction,1138,"9,450",2 BHK Apartment in M3M Antalya Hills Phase I,Sector 79,properties for sale in Gurgaon,Approved by RERA,2.0,M3M Antalya Hills Phase I,M3M,Apartment
3,40000000.0,Ready to move,4500,"8,888",4 BHK Independent Floor,Sector 57,MM India Pvt Ltd,Not approved by RERA,4.0,Outside Socity,Outside,Plot
4,24000000.0,Under Construction,1800,"13,333",3 BHK Independent Floor in Anant Raj Estate Plots,Sector 63,MM India Pvt Ltd,Approved by RERA,3.0,Anant Raj Estate Plots,Anant,Floor

In [12]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 19515
Columns: 12

In [13]:
df.columns.tolist()

['Price',
 'Status',
 'Area',
 'Rate per sqft',
 'Property Type',
 'Locality',
 'Builder Name',
 'RERA Approval',
 'BHK_Count',
 'Socity',
 'Company Name',
 'Flat Type']

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19515 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          19515 non-null  str
 1   Status         19515 non-null  str
 2   Area           19515 non-null  int64
 3   Rate per sqft  19515 non-null  str
 4   Property Type  19515 non-null  str
 5   Locality       19515 non-null  str
 6   Builder Name   19515 non-null  str
 7   RERA Approval  19515 non-null  str
 8   BHK_Count      19515 non-null  float64
 9   Socity         19515 non-null  str
 10  Company Name   19515 non-null  str
 11  Flat Type      19515 non-null  str
dtypes: float64(1), int64(1), str(10)
memory usage: 1.8 MB

In [15]:
df.describe()

                Area     BHK_Count
count   19515.000000  19515.000000
mean     2545.455752      3.229772
std      9550.629288      4.923873
min        60.000000      0.000000
25%      1423.000000      3.000000
50%      2000.000000      3.000000
75%      2800.000000      4.000000
max    958320.000000    132.000000

In [16]:
df.isnull().sum()

Price            0
Status           0
Area             0
Rate per sqft    0
Property Type    0
Locality         0
Builder Name     0
RERA Approval    0
BHK_Count        0
Socity           0
Company Name     0
Flat Type        0
dtype: int64

In [17]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage.sort_values(ascending=False))

Price            0.0
Status           0.0
Area             0.0
Rate per sqft    0.0
Property Type    0.0
Locality         0.0
Builder Name     0.0
RERA Approval    0.0
BHK_Count        0.0
Socity           0.0
Company Name     0.0
Flat Type        0.0
dtype: float64

In [18]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5292

In [19]:
df.nunique().sort_values()

RERA Approval       2
Status              4
Flat Type           6
BHK_Count          25
Locality          245
Company Name      269
Builder Name      725
Socity            967
Price            1758
Property Type    1848
Area             2038
Rate per sqft    3928
dtype: int64

In [20]:
df_clean = df.copy()

print("Original shape:", df.shape)
print("Working copy shape:", df_clean.shape)

Original shape: (19515, 12)
Working copy shape: (19515, 12)

In [21]:
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 5292

In [22]:
df_clean = df_clean.drop_duplicates()

print("Shape after removing duplicates:", df_clean.shape)

Shape after removing duplicates: (14223, 12)

In [23]:
missing = df_clean.isnull().sum().sort_values(ascending=False)

print(missing)

Price            0
Status           0
Area             0
Rate per sqft    0
Property Type    0
Locality         0
Builder Name     0
RERA Approval    0
BHK_Count        0
Socity           0
Company Name     0
Flat Type        0
dtype: int64

In [24]:
missing_percentage = (
    df_clean.isnull().sum() / len(df_clean) * 100
).sort_values(ascending=False)

print(missing_percentage)

Price            0.0
Status           0.0
Area             0.0
Rate per sqft    0.0
Property Type    0.0
Locality         0.0
Builder Name     0.0
RERA Approval    0.0
BHK_Count        0.0
Socity           0.0
Company Name     0.0
Flat Type        0.0
dtype: float64

In [25]:
df_clean["Price"] = (
    df_clean["Price"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_clean["Rate per sqft"] = (
    df_clean["Rate per sqft"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_clean["Price"] = pd.to_numeric(
    df_clean["Price"],
    errors="coerce"
)

df_clean["Rate per sqft"] = pd.to_numeric(
    df_clean["Rate per sqft"],
    errors="coerce"
)

print(df_clean[["Price", "Rate per sqft"]].dtypes)

Price            float64
Rate per sqft      int64
dtype: object

In [26]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 14223 entries, 0 to 19514
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Price          14223 non-null  float64
 1   Status         14223 non-null  str
 2   Area           14223 non-null  int64
 3   Rate per sqft  14223 non-null  int64
 4   Property Type  14223 non-null  str
 5   Locality       14223 non-null  str
 6   Builder Name   14223 non-null  str
 7   RERA Approval  14223 non-null  str
 8   BHK_Count      14223 non-null  float64
 9   Socity         14223 non-null  str
 10  Company Name   14223 non-null  str
 11  Flat Type      14223 non-null  str
dtypes: float64(2), int64(2), str(8)
memory usage: 1.4 MB

In [27]:
df_clean[["Price", "Rate per sqft"]].isnull().sum()

Price            0
Rate per sqft    0
dtype: int64

In [28]:
df_clean[["Price", "Area", "Rate per sqft", "BHK_Count"]].describe()

              Price           Area  Rate per sqft     BHK_Count
count  1.422300e+04   14223.000000   14223.000000  14223.000000
mean   3.995377e+07    2621.755959   15296.143992      3.266189
std    5.755291e+07   11125.298077   18761.002333      5.496692
min    9.500000e+04      60.000000     100.000000      0.000000
25%    1.410000e+07    1424.000000    8368.000000      2.000000
50%    2.620000e+07    2015.000000   12380.000000      3.000000
75%    4.550000e+07    2840.500000   18500.000000      4.000000
max    1.226300e+09  958320.000000  310000.000000    132.000000

In [29]:
df_clean[["Price", "Area", "Rate per sqft", "BHK_Count"]].describe()

              Price           Area  Rate per sqft     BHK_Count
count  1.422300e+04   14223.000000   14223.000000  14223.000000
mean   3.995377e+07    2621.755959   15296.143992      3.266189
std    5.755291e+07   11125.298077   18761.002333      5.496692
min    9.500000e+04      60.000000     100.000000      0.000000
25%    1.410000e+07    1424.000000    8368.000000      2.000000
50%    2.620000e+07    2015.000000   12380.000000      3.000000
75%    4.550000e+07    2840.500000   18500.000000      4.000000
max    1.226300e+09  958320.000000  310000.000000    132.000000

In [30]:
print(df_clean["BHK_Count"].value_counts().sort_index())

BHK_Count
0.0       999
1.0       251
2.0      2337
3.0      6150
4.0      3723
5.0       587
6.0        89
7.0        16
8.0        10
9.0         4
10.0        5
12.0        3
15.0        3
16.0        1
34.0        1
39.0        1
45.0        1
47.0        1
89.0        1
95.0        5
99.0       25
102.0       1
112.0       3
114.0       5
132.0       1
Name: count, dtype: int64

In [31]:
df_clean.nlargest(10, "Area")[[
    "Area",
    "BHK_Count",
    "Price",
    "Rate per sqft",
    "Property Type",
    "Locality"
]]

,Area,BHK_Count,Price,Rate per sqft,Property Type,Locality
17364,958320,0.0,1.197000e+08,125,Residential Plot,37D Dwarka Exp Gurgaon
17799,653400,0.0,7.500000e+08,1147,Residential Plot in Baliawas farms,Baliawas
17327,435600,0.0,5.000000e+08,1147,Residential Plot,Baliawas
17455,435600,0.0,5.000000e+08,1147,Residential Plot,Baliawas
12102,87300,0.0,9.000000e+07,1030,Residential Plot,Sector 75
7700,40500,0.0,1.100000e+08,2716,Residential Plot in Suncity Sun City,Sector 54
2839,16500,6.0,1.226300e+09,74323,6 BHK Apartment in DLF Camellias,Sector 42
10419,16500,6.0,1.226300e+09,74323,6 BHK Apartment in DLF Camellias,Sector 42
2841,16000,6.0,1.189100e+09,74324,6 BHK Apartment in DLF Camellias,Sector 42
1959,15500,5.0,3.057000e+08,19725,5 BHK Apartment in Ambience Caitriona,Sector 24

In [32]:
df_clean.nlargest(10, "BHK_Count")[[
    "BHK_Count",
    "Area",
    "Price",
    "Rate per sqft",
    "Property Type",
    "Locality"
]]

,BHK_Count,Area,Price,Rate per sqft,Property Type,Locality
19467,132.0,3240,57000000.0,17592,Residential Plot in I block 132,South City II
10756,114.0,969,32200000.0,33358,Residential Plot in Emaar Business District Eb...,Sector 114
10757,114.0,1130,37600000.0,33339,Residential Plot in Emaar Business District Eb...,Sector 114
10758,114.0,1981,66000000.0,33342,Residential Plot in Emaar Business District Eb...,Sector 114
10759,114.0,1163,38700000.0,33347,Residential Plot in Emaar Business District Eb...,Sector 114
10760,114.0,1292,43000000.0,33350,Residential Plot in Emaar Business District Eb...,Sector 114
2135,112.0,1593,29900000.0,18777,Residential Plot in Rishali Luxe Residency 112,Sector 112
2136,112.0,1071,20100000.0,18777,Residential Plot in Rishali Luxe Residency 112,Sector 112
17309,112.0,1350,22500000.0,16666,Residential Plot in Rishali Luxe Residency 112,Sector 112
2375,102.0,1800,50000000.0,27777,Residential Plot in BPTP 102 Eden Estate,Sector 102

In [33]:
df_clean["BHK_Count"].value_counts().sort_index()

BHK_Count
0.0       999
1.0       251
2.0      2337
3.0      6150
4.0      3723
5.0       587
6.0        89
7.0        16
8.0        10
9.0         4
10.0        5
12.0        3
15.0        3
16.0        1
34.0        1
39.0        1
45.0        1
47.0        1
89.0        1
95.0        5
99.0       25
102.0       1
112.0       3
114.0       5
132.0       1
Name: count, dtype: int64

In [34]:
pd.crosstab(
    df_clean["Property Type"],
    df_clean["BHK_Count"]
)

BHK_Count,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,39.0,45.0,47.0,89.0,95.0,99.0,102.0,112.0,114.0,132.0
Property Type,,,,,,,,,,,,,,,,,,,,,
1 BHK Apartment,0,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1 BHK Apartment in Floors,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1 BHK Apartment in AVL 36,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1 BHK Apartment in Adani Aangan,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1 BHK Apartment in Ameya Sapphire Eighty Three,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residential Plot in south city 1 N Block,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Residential Plot in south city 1 P Block,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Residential Plot in south city 1 Q Block,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Residential Plot in south city 1 premium Block,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Residential Plot in u block,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df_clean[df_clean["BHK_Count"] > 10][[
    "BHK_Count",
    "Area",
    "Price",
    "Rate per sqft",
    "Property Type",
    "Locality",
    "Flat Type"
]].head(20)

,BHK_Count,Area,Price,Rate per sqft,Property Type,Locality,Flat Type
141,39.0,3312,52500000.0,15851,Residential Plot in Reputed Builder Plot Secto...,Sector 39,Plot
2135,112.0,1593,29900000.0,18777,Residential Plot in Rishali Luxe Residency 112,Sector 112,Plot
2136,112.0,1071,20100000.0,18777,Residential Plot in Rishali Luxe Residency 112,Sector 112,Plot
2375,102.0,1800,50000000.0,27777,Residential Plot in BPTP 102 Eden Estate,Sector 102,Plot
7593,99.0,5805,33500000.0,5776,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7594,99.0,3096,17800000.0,5777,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7595,99.0,5893,34000000.0,5776,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7596,99.0,3539,20400000.0,5777,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7597,99.0,2322,13400000.0,5777,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7598,99.0,4518,26100000.0,5777,Residential Plot in Uppal Gurgaon 99,Sector 99,Plot
7643,95.0,1350,11200000.0,8333,Residential Plot in Solutrean Gateway95,Sector 95,Plot
7644,95.0,1252,10400000.0,8333,Residential Plot in Solutrean Gateway95,Sector 95,Plot
10756,114.0,969,32200000.0,33358,Residential Plot in Emaar Business District Eb...,Sector 114,Plot
10757,114.0,1130,37600000.0,33339,Residential Plot in Emaar Business District Eb...,Sector 114,Plot
10758,114.0,1981,66000000.0,33342,Residential Plot in Emaar Business District Eb...,Sector 114,Plot
10759,114.0,1163,38700000.0,33347,Residential Plot in Emaar Business District Eb...,Sector 114,Plot
10760,114.0,1292,43000000.0,33350,Residential Plot in Emaar Business District Eb...,Sector 114,Plot
12107,95.0,1350,15000000.0,11111,Residential Plot in Solutrean Gateway95,Sector 95,Plot
15605,89.0,1620,8550000.0,5277,Residential Plot in Orris Market 89,Sector 89,Plot
16515,95.0,1252,10400000.0,8333,Residential Plot in Solutrean Gateway95,Sector 95,Plot